# general configuration
url: https://robertoreale.me
baseurl: '/virtuosodba'

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/huge-left-outer-join-46433a.png"
  # author will appear under the avatar (optional)
  author: "The Virtuoso DBA"
  # tagline will appear under the title (optional)
  tagline: "How to improve database administration skills through SQL mastery"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .travis.yml

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
destination: _site
username: robertoreale
repo: virtuosodba
branch: master
