CREATE PROFILE PERMANENTE LIMIT 
COMPOSITE_LIMIT  DEFAULT
SESSIONS_PER_USER  DEFAULT
CPU_PER_SESSION  DEFAULT
CPU_PER_CALL  DEFAULT
LOGICAL_READS_PER_SESSION  DEFAULT
LOGICAL_READS_PER_CALL  DEFAULT
IDLE_TIME  DEFAULT
CONNECT_TIME  DEFAULT
PRIVATE_SGA  DEFAULT
FAILED_LOGIN_ATTEMPTS  DEFAULT
PASSWORD_LIFE_TIME  UNLIMITED
PASSWORD_REUSE_TIME  DEFAULT
PASSWORD_REUSE_MAX  DEFAULT
PASSWORD_VERIFY_FUNCTION  DEFAULT
PASSWORD_LOCK_TIME  DEFAULT
PASSWORD_GRACE_TIME  UNLIMITED;